In [1]:
import pandas as pd

In [2]:
df = pd.read_table('SportPoliticalNewsMultiClass', sep='\t', header = None, names = ['label', 'news'])

In [3]:
df.head()

label                                               news
0  political  Fakhrul urged the government to step down imme...
1  political  Nayapaltan will witness a human sea on Thursda...
2  political  Welcoming the new political platform bringing ...
3  political  All Ganatantra Mancha leaders are unimportant ...
4  political  Quader: BNP’s threat to resist polls will not ...

In [4]:
df['label'] = df.label.map({'political' : 0, 'cricket' : 1, 'football' : 2, 'badminton' : 3})
df.head()

label                                               news
0      0  Fakhrul urged the government to step down imme...
1      0  Nayapaltan will witness a human sea on Thursda...
2      0  Welcoming the new political platform bringing ...
3      0  All Ganatantra Mancha leaders are unimportant ...
4      0  Quader: BNP’s threat to resist polls will not ...

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df['news'], df['label'], test_size=0.1, random_state = 1)

In [7]:
print("Original Dataset Contains", df.shape[0], "news")

Original Dataset Contains 50 news


In [8]:
print("Training set Contains", X_train.shape[0], "news")

Training set Contains 45 news


In [9]:
print("Testing set Contains", X_test.shape[0], "news")

Testing set Contains 5 news


In [10]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
count_vector = CountVectorizer()

In [12]:
train = count_vector.fit_transform(X_train)
train

<45x368 sparse matrix of type '<class 'numpy.int64'>'
	with 590 stored elements in Compressed Sparse Row format>

In [13]:
test = count_vector.transform(X_test)
test

<5x368 sparse matrix of type '<class 'numpy.int64'>'
	with 31 stored elements in Compressed Sparse Row format>

In [14]:
from sklearn.naive_bayes import MultinomialNB

In [15]:
naive_bayes = MultinomialNB()

In [16]:
naive_bayes.fit(train, y_train)

MultinomialNB()

In [17]:
import numpy as np

predictions = naive_bayes.predict(test)

In [18]:
print(np.mean(predictions == y_test))

0.4


In [19]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predictions))

[[2 0 0 0]
 [0 0 0 2]
 [1 0 0 0]
 [0 0 0 0]]


In [23]:
naive_bayes.predict(count_vector.transform(['Australia batter David Warner took to social media and congratulated Sindhu on winning her first CWG gold medal']))

array([3], dtype=int64)